name       : libmongoc
version    : 1.20.0
release    : 5
source     :
    - https://github.com/mongodb/mongo-c-driver/releases/download/1.20.0/mongo-c-driver-1.20.0.tar.gz : a97242866212bdcf9dfb8030b31a32eef9ff83082b34e1027339c805a3c50b0d
homepage   : https://docs.mongodb.com/drivers/c/
license    : Apache-2.0
component  : programming.library
summary    : A high-performance MongoDB driver for C
description: |
    The MongoDB C Driver, also known as libmongoc, is a library for using MongoDB from C applications, and for writing MongoDB drivers in higher-level languages.
builddeps  :
    - pkgconfig(icu-io)
    - pkgconfig(libsasl2)
    - pkgconfig(libzstd)
    - snappy-devel
setup      : |
    %cmake_ninja -DENABLE_STATIC=OFF -DENABLE_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share
