name       : libmongoc
version    : 1.18.0
release    : 2
source     :
    - https://github.com/mongodb/mongo-c-driver/releases/download/1.18.0/mongo-c-driver-1.18.0.tar.gz : db9bfc28355fe068c88b00974ca770a5449c7931b66f2895c9fbf2104d883992
homepage   : https://docs.mongodb.com/drivers/c/
license    : Apache-2.0
component  : programming.library
summary    : A high-performance MongoDB driver for C
description: |
    The MongoDB C Driver, also known as libmongoc, is a library for using MongoDB from C applications, and for writing MongoDB drivers in higher-level languages.
builddeps  :
    - pkgconfig(icu-io)
    - pkgconfig(libsasl2)
    - pkgconfig(libzstd)
    - snappy-devel
setup      : |
    %cmake_ninja -DENABLE_STATIC=OFF -DENABLE_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share
