name       : libmongoc
version    : 1.22.1
release    : 7
source     :
    - https://github.com/mongodb/mongo-c-driver/releases/download/1.22.1/mongo-c-driver-1.22.1.tar.gz : 762735344e848bb2f100154ed2f7b0f8c9b25e37eafb2b79b54bf99c15a7c318
homepage   : https://docs.mongodb.com/drivers/c/
license    : Apache-2.0
component  : programming.library
summary    : A high-performance MongoDB driver for C
description: |
    The MongoDB C Driver, also known as libmongoc, is a library for using MongoDB from C applications, and for writing MongoDB drivers in higher-level languages.
builddeps  :
    - pkgconfig(icu-io)
    - pkgconfig(libsasl2)
    - pkgconfig(libzstd)
    - snappy-devel
setup      : |
    %cmake_ninja -DENABLE_STATIC=OFF -DENABLE_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share
